### ISSUE TITLE
[COVSUMMARY] & [PREGSUMMARY] responses to question are on new line

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#103]
![Screen Shot 2022-05-13 at 12 19 29 PM](https://user-images.githubusercontent.com/83971268/168325468-c8aa1532-c962-41a2-848c-90741521b305.png)

All of the options are listed below for clarity

*Instructions:  [display if PREG6-PREG11 were displayed to respondent]

Pregnancy number: 
Age when pregnancy began: [response from PREG4] 
Outcome of pregnancy: [response from PREG5] 
Number of infants: [response from PREG6]*
Method of delivery: [response from PREG7]* 
Did you breastfeed: [response from PREG8]*
Number of months of breastfeeding: [response from PREG9]*
Did you have gestational diabetes: [response from PREG10]*
Did you have pre-eclampsia or eclampsia: [response from PREG11]*

**Comment by cusackjm** [comment]
@boyd-mj @woodruffr @joshid-ims @huip-ims this is a low priority issue

**Comment by cusackjm** [comment]
Same with SLEEP2N
![image](https://user-images.githubusercontent.com/85582895/171703709-9259a33d-490b-4258-9c72-4daefc78a300.png)

**Comment by boyd-mj** [comment]
This has been fixed and will be included in the next delivery

**Comment by cusackjm** [comment]
@boyd-mj can you make the response to outcome of pregnancy on the same line? 
![Uploading image.png…]()

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/176758110-3fb9fe16-10a5-4f0a-bc0b-c93432024070.png)

**Comment by cusackjm** [comment]
also present in biospecimen qx for COVSUMMARY:
![image](https://user-images.githubusercontent.com/85582895/178329699-eb6e0128-4eda-4b94-a4b5-6d012d6c4500.png)

**Comment by joshid-ims** [comment]
The code for PREGSUMMARY is:

[PREGSUMMARY,displayif=greaterThanOrEqual(PREG3,#loop)] Here’s a summary of the information you shared about this pregnancy. If any of the information is incorrect, please select the “Back” button to update your responses. If all of the information is correct, please select the “Next” button to move forward.

Pregnancy number: #loop
Age when pregnancy began: {$PREG4} <br/>
|displayif=or(and(equals(PREG1,1),greaterThan(PREG3,#loop)),and(doesNotEqual(PREG1,1),greaterThanOrEqual(PREG3,#loop)))|Outcome of pregnancy: |
|displayif=equals(PREG5,0)|Live birth: single infant|
|displayif=equals(PREG5,1)|Live birth: twins, triplets, or higher multiples|
|displayif=equals(PREG5,2)|Stillbirth||displayif=equals(PREG5,3)|Live birth and stillbirth (loss of one or more of multiples)|
|displayif=equals(PREG5,4)|Miscarriage (pregnancy loss before 20 weeks)|
|displayif=equals(PREG5,5)|Termination||displayif=equals(PREG5,6)|Ectopic or tubal pregnancy (fertilized egg implants outside of the uterus)|
|displayif=equals(PREG5,99)|Prefer not to answer|<br/>
|displayif=or(equals(PREG5,1),equals(PREG5,3))|Number of infants:||displayif=equals(PREG6,0)| Two (Twins)||displayif=equals(PREG6,1)| Three (Triplets)||displayif=equals(PREG6,2)| Four or more|<br/>
|displayif=or(equals(PREG5,0),or(equals(PREG5,1),equals(PREG5,3)))|Method of delivery:||displayif=equals(PREG7,0)| Cesarean||displayif=equals(PREG7,1)| Vaginal|<br/>
|displayif=or(equals(PREG5,0),or(equals(PREG5,1),equals(PREG5,3)))|Did you breastfeed: ||displayif=equals(PREG8,1)| Yes||displayif=equals(PREG8,0)| No|<br/>
|displayif=equals(PREG8,1)|Number of months of breastfeeding: {$PREG9}|<br/>
|displayif=or(equals(PREG5,0),or(equals(PREG5,1),or(equals(PREG5,3),equals(PREG5,2))))|Did you have gestational diabetes:||displayif=equals(PREG10,1)| Yes||displayif=equals(PREG10,0)| No|<br/>
|displayif=or(equals(PREG5,0),or(equals(PREG5,1),or(equals(PREG5,3),equals(PREG5,2))))|Did you have pre-eclampsia or eclampsia:||displayif=equals(PREG11,1)| Yes||displayif=equals(PREG11,0)| No|

As you can see, there is no line break between "Outcome of Pregnancy" and "Live Birth". So not sure how to fix that. Maybe a PWA or renderer issue? 

The gaps between summary is where the code/summary is which is not being displayed. Nothing can be done about that too. 

 Biospecimen part: There are line breaks between summary details:

Symptoms present:|displayif=equals(SRVBLU_COV6_V1R0,1)| Yes||displayif=equals(SRVBLU_COV6_V1R0,0)| No| **<br/>**

|displayif=doesNotEqual(SRVBLU_COV6_V1R0,0)|Symptoms: ||displayif=equals(SRVBLU_COV8_V1R0,0)| Fever;||displayif=equals(SRVBLU_COV8_V1R0,1)| Body chills (feeling cold, shivering);||displayif=equals(SRVBLU_COV8_V1R0,2)| Body or muscle aches;||displayif=equals(SRVBLU_COV8_V1R0,3)| Weakness or fatigue (tiredness);||displayif=equals(SRVBLU_COV8_V1R0,4)| Confusion;||displayif=equals(SRVBLU_COV8_V1R0,5)| Trouble sleeping;||displayif=equals(SRVBLU_COV8_V1R0,6)| New loss of taste or smell;||displayif=equals(SRVBLU_COV8_V1R0,7)| Stuffy nose (nasal congestion);||displayif=equals(SRVBLU_COV8_V1R0,8)| Sore throat;||displayif=equals(SRVBLU_COV8_V1R0,9)| Cough;||displayif=equals(SRVBLU_COV8_V1R0,10)| Shortness of breath (trouble breathing);||displayif=equals(SRVBLU_COV8_V1R0,11)| Chest tightness;||displayif=equals(SRVBLU_COV8_V1R0,12)| Stomach pain;||displayif=equals(SRVBLU_COV8_V1R0,13)| Diarrhea or watery stool (poop);||displayif=equals(SRVBLU_COV8_V1R0,14)| Nausea (being sick to your stomach);||displayif=equals(SRVBLU_COV8_V1R0,15)| Vomiting (throwing up);||displayif=equals(SRVBLU_COV8_V1R0,16)| Rashes or other skin changes;||displayif=equals(SRVBLU_COV8_V1R0,17)| Conjunctivitis (pink eye);||displayif=equals(SRVBLU_COV8_V1R0,55)| Other: {$SRVBLU_COV8S_OTH_V1R0}|<br/>
<br/>
|displayif=doesNotEqual(SRVBLU_COV6_V1R0,0)|Overnight Hospitalization: ||displayif=equals(SRVBLU_COV12_V1R0,1)| Yes||displayif=equals(SRVBLU_COV12_V1R0,0)| No||displayif=equals(SRVBLU_COV12_V1R0,77)| Unsure|<br/>

So not sure what's going on. Could be PWA or renderer issue again?

**Comment by cusackjm** [comment]
@naiyume is this a PWA or renderer issue?

**Comment by cusackjm** [comment]
@danielruss unsure if Brian ever got to this issue. Do you know if this is a PWA or renderer issue.

**Comment by cusackjm** [comment]
This is still an issue in 9/30 stage testing 
![image](https://user-images.githubusercontent.com/85582895/193285445-e1f248f6-878e-4001-a8d2-151ec9540907.png)

**Comment by woodruffr** [comment]
@danielruss, I'm noting that your example shows it starting on the next line:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/81166095/193291673-083e9993-de0e-49c5-b901-bd47c6cb1610.png)

Is this something that you are addressing?

**Comment by danielruss** [comment]
I thought you wanted it that way, so I put newlines in the markdown.  Just remove the newlines in the markdown and it will be on the same line.

**Comment by joshid-ims** [comment]
@cusackjm How would you like it in Module 2? Like this:

![image](https://user-images.githubusercontent.com/64986739/193342422-11eb3b82-03ac-43c5-afa2-55d504c4a34f.png)

Or like this:

![image](https://user-images.githubusercontent.com/64986739/193342533-6e952b49-aac6-4e8f-b268-b0790d671a09.png)

**Comment by joshid-ims** [comment]
Yes, it is.

**Comment by cusackjm** [comment]
No, Option 2 is:
question: response
question: response

question: 
response


question: response
question: response


question: response

question: response

Can we remove the extra space and always have the responses on the same line as the question?

**Comment by guinevere83** [comment]
This has passed internal testing.

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/194570369-9b62f75f-9c65-4d74-8f7c-7ec8def9366c.png)

**Comment by boyd-mj** [comment]
@joshid-ims @danielruss any idea if this is a markup or PWA issue?

@cusackjm there was no screenshot attached to your email.

From: Cusack, Julie (NIH/NCI) [C] <julie.cusack@nih.gov> 
Sent: Friday, October 7, 2022 10:03 AM
To: Boyd-Morin, Jennifer (IMS) <Boyd-MorinJ@imsweb.com>; Petersen, Tony (NIH/NCI) [C] <tony.petersen@nih.gov>; Gerlanc, Nicole (NIH/NCI) [E] <nicole.gerlanc@nih.gov>; Gaudet, Mia (NIH/NCI) [E] <mia.gaudet@nih.gov>; Cunnane, Aileen (NIH/NCI) [C] <aileen.cunnane@nih.gov>; Dowling, Kelsey (NIH/NCI) [C] <kelsey.dowling@nih.gov>; Russ, Daniel (NIH/NCI) [E] <druss@mail.nih.gov>
Cc: Johnson, Davin (NIH/NCI) [C] <davin.johnson@nih.gov>; Barra, Gene (NIH/NCI) [C] <gene.barra@nih.gov>; Woodruff, Rose (IMS) <WoodruffR@imsweb.com>
Subject: RE: Updated Module 1 & 2 Surveys Delivered

Hi,

Module 1: Issue fixed and closed.

Module 2: [[COVSUMMARY] & [PREGSUMMARY] responses to question are on new line · Issue #103 · episphere/questionnaire (github.com)](https://github.com/episphere/questionnaire/issues/103) **not fixed when going to the next question and clicking back (see screenshot)**

Best,
Julie

**Comment by danielruss** [comment]
in quest dev tool (https://episphere.github.io/quest/):
![image](https://user-images.githubusercontent.com/3767675/194616925-76ee82da-e11c-420c-bfc1-db4ab28e66ca.png)

I'll test in PWA...

**Comment by cusackjm** [comment]
The screenshot is in the GitHub issue

Best,
Julie

Julie Cusack [C] * Operational Development Coordinator
Division of Cancer Epidemiology and Genetics
National Cancer Institute, National Institutes of Health
9609 Medical Center Drive, Rockville, MD 20850
[C] N4 Solutions, LLC
E: ***@***.******@***.***>
P: 240-276-5861

From: boyd-mj ***@***.***>
Sent: Friday, October 7, 2022 1:14 PM
To: episphere/questionnaire ***@***.***>
Cc: Cusack, Julie (NIH/NCI) [C] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [episphere/questionnaire] [COVSUMMARY] & [PREGSUMMARY] responses to question are on new line (Issue #103)


@joshid-ims<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjoshid-ims&data=05%7C01%7Cjulie.cusack%40nih.gov%7C5ee3d465d05945e1e55108daa8875b29%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638007596547440233%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=K8TiEwxJm9DPodpC%2BVMQskDLhXhJ%2B2YqIYrIDdPmQ9A%3D&reserved=0> @danielruss<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdanielruss&data=05%7C01%7Cjulie.cusack%40nih.gov%7C5ee3d465d05945e1e55108daa8875b29%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638007596547908886%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=j0Alts%2FTOqzK77FQAuM0k2Jq4TQtkZJdHmVC68%2F2dz4%3D&reserved=0> any idea if this is a markup or PWA issue?

@cusackjm<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcusackjm&data=05%7C01%7Cjulie.cusack%40nih.gov%7C5ee3d465d05945e1e55108daa8875b29%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638007596547908886%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yBrH%2BRS%2FpJ4KT7qZoKbVq46YzeevyBlAWCI2jBg852k%3D&reserved=0> there was no screenshot attached to your email.

From: Cusack, Julie (NIH/NCI) [C] ***@***.******@***.***>
Sent: Friday, October 7, 2022 10:03 AM
To: Boyd-Morin, Jennifer (IMS) ***@***.******@***.***>; Petersen, Tony (NIH/NCI) [C] ***@***.******@***.***>; Gerlanc, Nicole (NIH/NCI) [E] ***@***.******@***.***>; Gaudet, Mia (NIH/NCI) [E] ***@***.******@***.***>; Cunnane, Aileen (NIH/NCI) [C] ***@***.******@***.***>; Dowling, Kelsey (NIH/NCI) [C] ***@***.******@***.***>; Russ, Daniel (NIH/NCI) [E] ***@***.******@***.***>
Cc: Johnson, Davin (NIH/NCI) [C] ***@***.******@***.***>; Barra, Gene (NIH/NCI) [C] ***@***.******@***.***>; Woodruff, Rose (IMS) ***@***.******@***.***>
Subject: RE: Updated Module 1 & 2 Surveys Delivered

Hi,

Module 1: Issue fixed and closed.

Module 2: [COVSUMMARY] & [PREGSUMMARY] responses to question are on new line * Issue #103 * episphere/questionnaire (github.com)<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fepisphere%2Fquestionnaire%2Fissues%2F103&data=05%7C01%7Cjulie.cusack%40nih.gov%7C5ee3d465d05945e1e55108daa8875b29%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638007596547908886%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=B2c5g0Vl0c0Gk5J2o9wCTwj34KVx%2FC0IyUtX99NhxNo%3D&reserved=0> not fixed when going to the next question and clicking back (see screenshot)

Best,
Julie

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fepisphere%2Fquestionnaire%2Fissues%2F103%23issuecomment-1271846971&data=05%7C01%7Cjulie.cusack%40nih.gov%7C5ee3d465d05945e1e55108daa8875b29%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638007596547908886%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UmeRRXxXkIB%2BFpTJoMhA6ax8eUcIuR9W51lU3Zh%2BwA4%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUM6IL3EY6SNWD2AEEWHUD3WCBK5LANCNFSM5V33Y7XQ&data=05%7C01%7Cjulie.cusack%40nih.gov%7C5ee3d465d05945e1e55108daa8875b29%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638007596547908886%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PRuwyRA5E1koNKBm4D06E1Nk9FmuFq0U%2B03%2BNUUMwoQ%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by woodruffr** [comment]
Has this been resolved?

**Comment by cusackjm** [comment]
@woodruffr I think so, I will double check when I test the latest Mod 2 delivery
