### ISSUE TITLE
[PERMTTHLOST] - [DENTURE] loop due to response at [HYGIENE]

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#113]
[HYGIENE] 0=Toothbrush, 4 = teeth-whiteners, 5 = Mouthwash
[BRUSH2] 2 = 3-5 times/week
[WHITE2] 0 = less than once per week
[MWUSE] 3 = Fluoride, 4 = Peroxide
[MWFLOURIDE] 1 = once or twice per week
[MWPEROX] 0= less than once per week
[PERMTTHLOST] 0 = NO
[DENTURE] 4 = dental implants

I had to click "NEXT" twice when submitting [DENTURE].  
Then, I was brought back to [PERMTTHLOST] and my "NO" answer was saved and so was "dental implants."  
I had to click "NEXT" twice again before I was brought to [DENTALCLEAN]

Worked with @naiyume on this and he mentioned that he could see the issue in the mark up.

**Comment by naiyume** [comment]
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/27040828/169596665-17aef386-58ef-4950-9792-bab9bcb0ff45.png">

PERMTTHLOST is referenced here and also in the SRVMW_MWUSE_V1R0. 

<img width="993" alt="image" src="https://user-images.githubusercontent.com/27040828/169596943-992842c6-095e-49c9-bed8-6e46bdaf8dfc.png">

I believe that this leads to the PERMTTHLOST question group looping twice.

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/27040828/169597105-36fff276-be07-4e5a-9f6c-53203f1de200.png">

The above picture shows the PERMTTHLOST question itself. I believe SRVMW_DENTURES_V1R0 will be called twice if No is answered because it is linked as a next and not a no response.

**Comment by huip-ims** [comment]
@naiyume @cunnaneaq @boyd-mj Hi Brian-For PERMTTHLOST, we previously tried:
![image](https://user-images.githubusercontent.com/82978291/169907669-749bf0e3-6102-4073-8a5f-3b43c41b33f2.png)
This resulted in the issue addressed in #94. If we take out the '#NR', then DENTURES is called twice.

Similar with HYGIENE:
![image](https://user-images.githubusercontent.com/82978291/169909449-4db6a5fb-bd47-4319-bbe5-852a4c11e725.png)
When '#NR' is in the code, it won't show the correct selections, as addressed in #93.

Is there an issue with Quest when '#NR' is in the code in these Select All That Apply question type, which worked fine in modules 1-4?

**Comment by naiyume** [comment]
@huip-ims I want to double check the logic that we are going for here. If we want the question to always go to SRVMW_DENTURES_V1R0 after the SRVMW__TEETHLOSTAI_V1R0 and SRVMW_TEETHLOSTD_V1R0 resolve, then just take out the SRVMW_DENTURES_V1R0 pointer from the 0 response. In the end, it should look like this
<img width="859" alt="image" src="https://user-images.githubusercontent.com/27040828/170726909-c7cd549a-f9a6-43ef-8ee2-83236a289834.png">
Basically, the question will always go to SRVMW_DENTURES_V1R0 after everything is resolved and will only go there once even if no is selected.

This is very simlar to the HYGIENE question.
![image](https://user-images.githubusercontent.com/27040828/170727134-128c7ea7-b6f3-4af8-911e-8203a974e3ff.png)
The above shouldn't need to be changed, but we would remove the SRVMW_PERMTTHLOST_V1R0 pointer from SRVW_MWUSE_V1R0
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/27040828/170727419-a757594c-5fe8-47f9-9d93-b44b3f6ca576.png">

Please let me know if this makes sense.

**Comment by huip-ims** [comment]
@naiyume @boyd-mj Thanks Brian - I've made some changes to the markup, and it's currently going through internal testing.
