### ISSUE TITLE
HOMEMOVEOUT, SEASADDYR2, SEASADDMOS radio button responses populating as null

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#205]
Mod 4 DEV Testing Issue
[Record of responses](https://nih.app.box.com/file/1071841445917?s=cw0prin4oyan3sxo5ciqhmnishqz7sfb): ("Test Scenario 1 JC" tab) 
Account: nciccctesting@gmail CID: 6416039811 

HOMEMOVEOUT= 0 "I still live here" (CID: 678602069) is populating as "null"
SEASADDYR2= 0 "I still spend time here" (CID: 196962759) is populating as "null"
SEASADDMOS= 0 "Less than 1 month" (CID: 232063618) is populating as "null"

Unsure if this is relevant, but these questions are all "text box plus check box" question types, and the numeric text responses are saving

@boyd-mj @danielruss is this a markup, quest, or PWA issue?

**Comment by cunnaneaq** [comment]
Account: nciccctesting2@gmail.com, Connect ID: 8985865993

In the scenario I tested - [Record of responses](https://nih.app.box.com/file/1071841445917?s=cw0prin4oyan3sxo5ciqhmnishqz7sfb): ("Testing Scenario 2 AC" tab), I recorded the same responses as @cusackjm and the same responses are populating as null.

In addition:
CHILDADD5 = 0 "Lived there since birth" (CID: 858353109) is populating as "null"
CHILDADD6 = 77 "Unavailable/Unknown" (CID: 178420302) is populating as "null

**Comment by cusackjm** [comment]
@KELSEYDOWLING7 can you elaborate on what you saw on your end

**Comment by KELSEYDOWLING7** [comment]
@danielruss  Oh ok great! Thank you. 

That doesn't follow the data dictionary, D_728155643.D_728155643 should be D_728155643.D_867247249 for still live here, which was populating no data. That seems a little odd/problematic but when I look at that new variable (D_728155643.D_728155643) I can see the data.

**Comment by danielruss** [comment]
@KELSEYDOWLING7   Not a problem.  The issue is with the coding.  If you want this, you need to markup to look like this:

```
[X] LALA

[D_728155643?] What year did you move out of|

If you still live at this address, select “I still live here.”
Year moved out |__|__|__|__|id=D_943813942|

[678602069*:D_867247249] I still live here

[END] all done |displayif=valueEquals("D_728155643.D_728155643","678602069")| I still live here ||displayif=exists("D_943813942")|{$D_943813942}|
```

Notice the **[678602069\*:D_867247249]**  The colon sets the NAME of the checkboxes (so we know that this set of checkboxes go together. Each as a different id -- all html elements must have unique Id's -- and different values -- so we know which checkbox was selected.

This is not often an issue, because when you don't select a name, I give you a default name, which you probably guessed is the question Id.

**Comment by danielruss** [comment]
There is a small bug in quest that this discussion pointed out see: episphere/quest#416 .

**Comment by KELSEYDOWLING7** [comment]
@danielruss @cusackjm   Do we know why this new variable may have been created instead of matching the DD?

**Comment by KELSEYDOWLING7** [comment]
Ok. Is there a way to invite Jake to view this Github page as well? I think it would be helpful for flattening but I'm not able to invite him.

**Comment by danielruss** [comment]
@KELSEYDOWLING7 This is open-source, all he needs is the url https://github.com/episphere/questionnaire/issues/205

**Comment by danielruss** [comment]
@cusackjm @boyd-mj @anthonypetersen @FrogGirl1123  **WARNING** I am making a change in the code that MAY have downstream effects.  This issue pointed out a problem with QUEST that requires a fix.  I am not sure if you will every run into the problem, but if you use the "data-reset" the  asterisk in the markdown  it clear items that have the same NAME.  I have changed it to clear all inputs in the question.  I don't think this will break anything, but KEEP AN EAR OUT if the help desk reports errors where participants complain that question are clearing on them.
