### ISSUE TITLE
Remove COVID-19 questions from Blood/Urine/Mouthwash Survey (Research Appt Survey)

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#217]
Edits involved:
1. COVID-19 section questions removed from survey
2. Edited skip logic for [SrvBlU_REPROINTRO_v1r0] and [SrvBlU_CONTRACEPT_v1r0] 

DCEG document (edits in tracked changes): https://nih.app.box.com/file/1147379738700 
IMS document (edits in tracked changes): https://nih.app.box.com/file/1147389051572

@FrogGirl1123 @woodruffr, just want to confirm DD edits before I make them, the COVID-19 variables should be denoted as deprecated?

**Comment by cusackjm** [comment]
Questions deprecated from DD on 2/23/2023

**Comment by joshid-ims** [comment]
@cusackjm While checking the Mouthwash survey for this, I noticed that some of the question IDs are changed from V1 to V2. Am I supposed to make that change?

**Comment by cusackjm** [comment]
@joshid-ims my understanding was that rose had requested this @woodruffr did i misunderstand things?

**Comment by woodruffr** [comment]
From the 2/15/2023 NCI/IMS Meeting Minutes: 
ii.	Because Blood/Urine/Mouthwash was pushed to production but Blood/Urine and Mouthwash have not been published, the questions in both had different version numbers, but shared Variable Names and Concept IDs. 
1.	 New rule: If a question is in multiple surveys (same Variable Name, Question Text, concept IDs, and responses) and one survey warrants versioning up, it will be versioned up in all surveys in which it appears.

The V2 is to maintain consistency, which will help with the QC.

**Comment by cusackjm** [comment]
@woodruffr sounds good. I will add that to my qx development SOP.

*also reopening this and will close it after we confirm the edits in dev and stage testing

**Comment by cusackjm** [comment]
confirmed covid section removed from blood/urine/mouthwash in dev testing on 6/14/23
https://nih.app.box.com/file/1237785207288
