### ISSUE TITLE
put TESTHER_INTRO on same screen as TESTHER

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#246]
![image](https://github.com/episphere/questionnaire/assets/85582895/dc67ae0c-ab6c-4a54-aaa6-3ea0b786b4cf)

**Comment by woodruffr** [comment]
@cusackjm We have an internal note dated August 16th saying that as per your communication this change will not be made. Previously when that happened you closed the issues (#249 & #250). Do we have a convention for content change requests that get canceled because of technical issues in making them? I just want to be sure that all the issues get tracked and will need to know whether I should incluce this and 249 & 250 in the delivery log notes. We did make changes that had to be reverted, so it should be tested. Your thoughts?

**Comment by cusackjm** [comment]
Hi Rose, I had must've missed this issue when I denoted those issues as "closed not as planned", instead of "closed with comment". That is a good idea, we do not have a convention for documenting issues that are closed not as planned due to technical issues, but I will create a sheet that includes the issue description, issue link, decision background, data of decision, and date closed. Then in the delivery notes we can link to that sheet to document what could not get fixed

**Comment by woodruffr** [comment]
Sounds great. Let's mention this in Wednesday's meeting so it officially gets entered somewhere as a part of the SOP (Wednesday's minutes and decision log that Jen keeps).

**Comment by joshid-ims** [comment]
@cusackjm, So we are not making these changes?

**Comment by cusackjm** [comment]
@joshid-ims no, I believe I had "closed not as planned" because the edits were not possible

**Comment by joshid-ims** [comment]
Ok, thanks.
