### ISSUE TITLE
SECTION 3 (Physical Activity) heading missing intro text

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#247]
![image](https://github.com/episphere/questionnaire/assets/85582895/a5f55444-4549-415f-89be-620acde3c354)

![image](https://github.com/episphere/questionnaire/assets/85582895/98bd9a43-e839-4ae0-aed0-957bd963923e)

**Comment by huip-ims** [comment]
@cusackjm Julie - In your snapshot above, it shows "Physical Activity at Work", which is a secondary heading right before the WORKACT grid. See documentation below. We can try to display the secondary heading "Physical Activity at Work" on the same page as the grid, rather than on 2 separate pages. Will this work for you?
![image](https://github.com/episphere/questionnaire/assets/82978291/f55a7462-d5cd-415e-9269-72362a3994a2)

**Comment by cusackjm** [comment]
yes

**Comment by cusackjm** [comment]
confirmed fix in dev testing on 11/3/2023
