### ISSUE TITLE
Put SITTING Grid/source question text on same screen as SITTINGA-D

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#249]
![image](https://github.com/episphere/questionnaire/assets/85582895/2e4d62dc-73c2-4e6a-8cc7-d36aa14485f3)
![image](https://github.com/episphere/questionnaire/assets/85582895/35620200-2436-4abc-b52e-33f31b3ce232)

Put SITTING Grid/source question text on same screen as SITTINGA-D. remove "typical hours per DAY" (similar to how SITTING and SITTINGA-D are displayed (typical hours per DAY is not displayed)
Sitting example: 
![image](https://github.com/episphere/questionnaire/assets/85582895/96565392-22db-4ceb-90a8-abda3cf21090)

**Comment by joshid-ims** [comment]
displayif inside grid statement does not work.

|grid?|id="GRID_SITTING"|<b>Sitting</b> <br/><br/>During the <b>past 12 months</b>, about how many <b>hours per day</b> did you usually spend doing each of these activities |displayif=valueEquals("WORK",1)|outside of work||[

Maybe because of two vertical lines? ||

@danielruss ?

**Comment by joshid-ims** [comment]
@cusackjm this issue is similar to https://github.com/episphere/questionnaire/issues/250 Pete contacted you for. For that issue, since this cannot be done, the change is cancelled. Should we do that for this issue too?

**Comment by cusackjm** [comment]
Yes
