### ISSUE TITLE
Put HOUSE1 Grid/source question text on same screen as HOUSE1A-E

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#250]
Same as: https://github.com/episphere/questionnaire/issues/249

Put on same screen:
![image](https://github.com/episphere/questionnaire/assets/85582895/b64b7491-10aa-4d5a-8c35-1f9da0af8a8f)
![image](https://github.com/episphere/questionnaire/assets/85582895/56ef521b-993a-4a17-8eef-419e21a32af0)

**Comment by huip-ims** [comment]
@cusackjm Julie - We tried this approach previously. Because there is conditional display text ("outside of work") within in intro,  the heading and intro text cannot be added to the grid to be displayed on the same screen.

![image](https://github.com/episphere/questionnaire/assets/82978291/3cc77834-445d-45fc-9271-005c0f894cda)

**Comment by cusackjm** [comment]
ok that is fine. I will mark as unable to resolve and close issue
