### ISSUE TITLE
Smirnoff is Missing registered trademark symbol (®)

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#312]
Smirnoff is missing registered trademark symbol (®) in:
1. ALCOHOL8= 55 response text 
2. OTHALC1 question text
3. OTHALC2 question text
4. ALCLIFE4A-H= 55 response text

![image](https://github.com/episphere/questionnaire/assets/85582895/aaf15877-09eb-4289-bfe9-b84bbccdcd02)
![image](https://github.com/episphere/questionnaire/assets/85582895/5eeaf0dd-bc96-4ec5-89a2-61b137265145)

**Comment by woodruffr** [comment]
@cusackjm, related to documentation for this. The Smirnoff only shows up in the Variable Label, which we know is only used for data labels when the data gets sent to researchers in the future (as far as I know). Is it worth adding the trademark symbol to that in the dd? It won't need to be versioned because it doesn't change the question text, response text, or Variable Name.

**Comment by cusackjm** [comment]
@FrogGirl1123 do we have to add the "®" to the DD? Wondering if it would be ok to not add because the trademark characters sometimes get additional special characters added that I periodically delete

**Comment by danielruss** [comment]
@cusackjm make sure you type  `&reg;` to get the registered trademark symbol, not the special key.

**Comment by cusackjm** [comment]
Confirmed fix in dev testing using chrome, laptop on 1/5/2024
