### ISSUE TITLE
Update logic for HAIRFEM, HAIRMALE (display if AGE≥ 40)

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#319]
**Sorry this is last minute**, the display logic for HAIRFEM and HAIRMALE needs to be updated in regards to the participant age range expansion to 30. 
![image](https://github.com/episphere/questionnaire/assets/85582895/14e1f30a-6652-4620-8002-7a52f2de6adc)

**Comment by woodruffr** [comment]
@cusackjm, Above and in the Word document you use display if AGE≤ 40 but in the Questionnaire change log, you wrote "Added display directions to HAIRFEM, HAIRMALE so they are only displayed to participants over 40", which is what I believe you meant for it to be since the question asked about baldness patterns at age 40 it would be hard to answer if you were under 40. Please clarify and update the Questionnaire so that the change log and noted changes are congruent.

**Comment by cusackjm** [comment]
@woodruffr sorry that was my friday afternoon brain adding the wrong symbol in the logic. I will update that now.

**Comment by cusackjm** [comment]
confirmed fixed in dev testing on 1/23/2024
