### ISSUE TITLE
HOMEADD1_3 to HOMEADD11_3 Wording

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#32]
@cusackjm @freedmanne 

I believe we will need a Module 4 Questionnaire Word doc change for HOMEADD1_3 – HOMEADD11_3. For the first address it says something about where you live now. The 2nd and later addresses still say “before you moved to the place you live now?” That makes no sense for addresses 3-11.

We originally recommended against using 2nd, 3rd, 4th, etc. addresses if a street etc. was not provided because it was a loop. However, these are now all individual questions so we can change the language in each question if asked to do so. There are comments in the Word document, but the content wasn’t changed away from the “before you moved to the place you live now” language.

@boyd-mj @Davinkjohnson

**Comment by cusackjm** [comment]
Neal and I agree that we should not fill "before you moved to the place you live now" for 3rd, 4th, 5th, etc. addresses. We would like to instead fill the previous address that was reported.

**Comment by boyd-mj** [comment]
Hi @cusackjm, our team reviewed the changes in the Word document and discussed further. Two follow-up questions:

1. Per your email, we only want to make these changes for addresses 3+, so for the second address, we should retain the previous language of "the place you lived before the place you live now", correct? If so, that probably should be tweaked in the Word doc.

2. How important is it that the participant enters address 3 and beyond chronologically (or even how likely is it that they will be able to)? It would be a lot simpler to code and test if we used some other generic language like "What is the full street address of the place you lived before you lived at the previous address you provided?" rather than inserting the previous address. We can proceed with the changes as outlined, but thought I would mention this. 

Thanks,
Jen

**Comment by cusackjm** [comment]
Hi- for the purpose of these questions we need to know which address the person lived and the years that they lived there. We think it it easier to remember your next address if you are prompted with the address you previously listed before.

**Comment by boyd-mj** [comment]
Hi Julie,

Thanks for the feedback. We will work on these changes. 

Jen

**Comment by boyd-mj** [comment]
Hi @cusackjm I just wanted to follow up on the question below. Do you want to update the relevant section of the questionnaire to reflect this decision? We've made the code changes.

Thanks,
Jen

> Hi @cusackjm, our team reviewed the changes in the Word document and discussed further. Two follow-up questions:
> 
>     1. Per your email, we only want to make these changes for addresses 3+, so for the second address, we should retain the previous language of "the place you lived before the place you live now", correct? If so, that probably should be tweaked in the Word doc.
> 
> Thanks, Jen

**Comment by cusackjm** [comment]
Hi, no, we decided to please keep it as the directions state and fill the previous address for addresses 2-11.
