### ISSUE TITLE
Incorrect Skip Patterns/DisplayIf

### ISSUE THREAD

**Issue by woodruffr** [episphere/questionnaire#366]
These issues displayed or did not display erroneously. These involve Mark-up changes and don't require any NCI input. This issue is to document the changes so we can confirm when they are fixed.

![image](https://github.com/episphere/questionnaire/assets/81166095/4c69e255-8265-4d2c-b95a-1dd60dae7fff)

**Comment by woodruffr** [comment]
The updated Mark-up for this was delivered this morning.

**Comment by cusackjm** [comment]
can you provide the scenario and responses listed? This may not be an issue

**Comment by cusackjm** [comment]
Just want to confirm that the delivered markdown reflects this logic:

MULT2 is displayed if MULTIBIRTH= 1, 2, 3
![image](https://github.com/episphere/questionnaire/assets/85582895/7588800b-93a0-4997-acc1-c74973878e5f)

If MULTIBIRTH= 0 or NR, the participant should not see MULT2. 

In scenario 5, the tester should have skipped (i.e., MULTIBIRTH= NR), and then they should have not seen MULT2 for each sibling. Given that the tester saw MULT2 for each sibling, this issue was created. Just want to confirm that the updated markdown addressed the display issue that was related to MULTIBIRTH= NR

**Comment by joshid-ims** [comment]
Yes, that is what was tested after changes were made in the code. The NR was not taken into account in the code. I changed the logic to add that. It was just checking if it was not 0. Now code is checking if value is one of 1,2 or 3 and then displaying MULT2.

**Comment by cusackjm** [comment]
can i close this issue?

**Comment by guinevere83** [comment]
Thiis is resolved.
