### ISSUE TITLE
"Never" responses missing additional language in the response

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/questionnaire#44]
<img width="817" alt="Screen Shot 2022-03-16 at 9 47 36 AM" src="https://user-images.githubusercontent.com/83971268/158604301-77ca07f8-9b13-4d44-8af4-2ac82b5e3822.png">

**Comment by cusackjm** [comment]
issue still present in testing 4/29/22
account: 609-576-3460
Connect ID: 9393372061

**Comment by cusackjm** [comment]
@Davinkjohnson is this grouped in with the aesthetic issues that will be addressed later on?

**Comment by cusackjm** [comment]
Mod 2 Variables missing additional jargon in their "never" responses:
- CIG3 “Never smoked on a regular basis” 
- ECIG3 “Never used them on a regular basis” 
- CIGAR3 “Never smoked on a regular basis” 
- CHEW3 “Never used them on a regular basis” 
- HOOKAH3 “Never smoked on a regular basis” 
- PIPE3 “Never smoked on a regular basis” 
- SMMAR3 “Never smoked on a regular basis” 
- TOMAR “Never smoked on a regular basis” 
- ELMAR3 “Never vaped marijuana on a regular basis” 
- EAMAR3 “Never consumed marijuana in food or drinks on a regular basis” 
- THMAR3 “Never used THC concentrates via dabbing on a regular basis” 
- ALCOHOL4 “Never drank on a regular basis”

**Comment by boyd-mj** [comment]
@FrogGirl1123

**Comment by FrogGirl1123** [comment]
Jen and I reviewed these a while ago while working on the harmonization.  From our perspective (@boyd-mj correct me if this is not your recollection), repeating part of the question in the "Never" response isn't necessary.  Did you drink on a regular basis? Never.  In the context of answering that specific question "Never" means the same things as "Never on a regular basis".  However, given that the question also asks about age I can see where the wording might be a little awkward.  "Never" should remain in the DD dictionary as the meaning with the harmonization is appropriate.  We can change the text in the mark-up back to the original if Neal feels strongly about it, but it is not an MVP change.

**Comment by cusackjm** [comment]
@FrogGirl1123 Neal does want it to be changed

**Comment by boyd-mj** [comment]
@FrogGirl1123 yes, your recollection is correct. Here's the decision from way back when:

From: Gerlanc, Nicole (NIH/NCI) [E] <nicole.gerlanc@nih.gov>
Sent: Tuesday, November 9, 2021 8:56 AM
To: Boyd-Morin, Jennifer (IMS) <Boyd-MorinJ@imsweb.com>
Subject: Resolution of the Nevers

Hi Jen,

The rest of the team is in agreement with how we would like to differentiate the “Never”s. For Questions like PAINREL8, where Never means “No” and the response option should be changed to “No” in the markup and the dictionary, so the use of the concept and associated ID is consistent. In the second instance, where Never means “Never”. We’ll need a new harmonized concept for Never. For the number coding, I was thinking we could use “44”

For both cases, both the markup and the concept response association in the data dictionary will have the simplified wording (e.g. Never instead of Never became regular vs Never smoked on a regular basis. Where “Never” means “No” the markup should be changed to “No”.

Please let me know if you have any follow-up questions.

Thanks,
Nicole 

Should we proceed with updating the markup only? Thanks!

**Comment by cusackjm** [comment]
MENSHIS & MENSHIS2 "never" responses are fixed in stage mod 2 testing 6/2/22

**Comment by cusackjm** [comment]
tested and fixed in mod 3 on 6/3
