### ISSUE TITLE
Menstrual Cycle Survey - Progress

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#64]
Menstrual Cycle Survey - Questionnaire Document is in the Biospecimens Folder (https://nih.box.com/s/ob9qmgexut0znk5yei9run6wbuw7wydw)

Menstrual Cycle Survey has information filled in in the Question Types Document, under the "Menstrual cycle" Tab

**Comment by woodruffr** [comment]
The link above didn't work for my access permissions, but I can access it here. https://app.box.com/file/942632162714?s=ob9qmgexut0znk5yei9run6wbuw7wydw

Since this is separate from the other questionnaire, please notify Jen by email that it is available for coding and copy Nicole and Davin.

**Comment by cusackjm** [comment]
Tab for Menstrual Cycle Survey DD added to Biospecimens DD: https://nih.box.com/s/8jwgcng4htgqi0t4kgj42ti4pt743dd2

**Comment by woodruffr** [comment]
The DD formatting looks good. We can add the Concept ID for Survey - 129084651. I'd recommend asking Nicole for the Secondary Source. You can use the "Notes" column as you see fit. I note that you added a Required to that column for MENS2, but not MENS1. It seems redundant since their is a separate column for Required.

**Comment by cusackjm** [comment]
survey concept ID was added.

**Comment by boyd-mj** [comment]
@cusackjm can we close this?

**Comment by cusackjm** [comment]
yes
