### ISSUE TITLE
PREWORKT2 responses are all shown: should only be responses selected in PREWORKT1

### ISSUE THREAD

**Issue by cusackjm** [episphere/questionnaire#76]
PREWORKT2 responses are all shown: should only be responses selected in PREWORKT1

Testing 4/21 in [dcegdaniel@gmail.com](mailto:dcegdaniel@gmail.com) Connect ID: 4235365942. I selected PREWORKT1= 2 and 55 but still saw every response in PREWORKT2

**Comment by cusackjm** [comment]
same with CURWORK

**Comment by guinevere83** [comment]
Was not able to reproduce this. Potentially any fixes made in https://github.com/episphere/questionnaire/issues/67 might resolve this.

**Comment by cusackjm** [comment]
issue still present in testing 4/29/22
account: 609-576-3460
Connect ID: 9393372061

**Comment by naiyume** [comment]
@cusackjm This should be resolved now. Please check this in the next batch of testing

**Comment by cunnaneaq** [comment]
[PREWORKT2] grid FIXED in 5/26 dev testing - Selected "motorcycle" and "other" in [PREWORKT1] and only saw those two selections in the [PREWORKT2] grid. Screenshots below.  Unable to test CURWORK grids in this scenario.

[PREWORKT1]
![Screen Shot 2022-05-26 at 11 42 17 AM](https://user-images.githubusercontent.com/83971268/170523427-dd489a82-c9b0-47d5-a99a-c481a82169e9.png)

[PREWORKT2]
![Screen Shot 2022-05-26 at 11 42 46 AM](https://user-images.githubusercontent.com/83971268/170523509-cd11b2bf-c49c-437a-aee3-98490d1f8a11.png)

**Comment by cusackjm** [comment]
confirmed fix 5/26
